version: '3.8'


volumes:
  market_database_data:
    name: database_data
    driver: local

networks:
  market_network:
    name: market_network
    driver: bridge

services:
  market_database:
    image: postgres:16.1-alpine3.18
    volumes:
      - market_database_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - market_network

  market_api:
    image: node:18-alpine
    container_name: market_api
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: market_api
    env_file: .env
    restart: always
    environment:
      - NODE_ENV=development
      - MARKET_API_PORT=5050
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@market_database/${POSTGRES_DB}?schema=public
    ports:
      - "5050:5050"
    depends_on:
      - market_database
    networks:
      - market_network
    volumes:
      - /c/Users/hikme/projects/wearplace/market/src:/usr/src/app/src
      - /c/Users/hikme/projects/wearplace/market/libs:/usr/src/app/libs

